### ISSUE TITLE
Info about metadata

### ISSUE THREAD

**Issue by matheushent** [gtatters/Thermimage#12]
This is issue isn't for feature suggestion or bugs itself; it's more about what some metadata really means.

I've been looking for info on the web but found nothing. I realised there are two metadata embedded on FLIR images called OffsetX and OffsetY. Any idea about what is it?

**Comment by gtatters** [comment]
I'm not sure.  It might be related to the mid x,y coordinate for the Region of Interest Box that tends to be in the centre of the image, but can be modified by the user.   Or possibly a location of an embedded picture within/on top of the thermal image space.  

The tags, incidentally, are named by Exiftool author.  Not sure they correspond precisely to FLIR nomenclature or not:

https://exiftool.org/TagNames/FLIR.html

**Comment by matheushent** [comment]
I would like to select the rectangle representing the thermal image in the embedded image extracted from the thermal. Any idea about doing it?

**Comment by gtatters** [comment]
not really, and it seems a task beyond me to work out.  Also, I don't really understand what you are asking.  When you extract the raw thermal image, it isn't embedded anywhere.  FLIR just makes it appear that way with the thumbnail jpg they include to facilitate compatibility, but the raw thermal image seems usually to be included and extracted fully when you use the -RawThermalImage tag with Exiftool.
I mainly wrote this package to deal just with the thermal image itself.  But FLIR jpgs can often have multiple images embedded in them, making a generic function difficult to write.  I think Exiftool can probably export multiple images that are found within a single .jpg, so you might need to do that part manually.  

This is reaching more into Exiftool expertise I am afraid.  :(

**Comment by matheushent** [comment]
Indeed, the issue really doesn't handle anything about this package, so I'm closing the issue.

**Comment by gtatters** [comment]
Ok, sorry I wasn't much help.  The challenge is that ideally I should have a fully ported version of Exiftool available for use in R, but that would take significant time and talent I lack.  :)
