### ISSUE TITLE
Error when loading FLIR jpg

### ISSUE THREAD

**Issue by lossberger** [gtatters/Thermimage#13]
When importing an FLIR jpg according to the instructions from https://github.com/gtatters/Thermimage (OS: Win 10) using the following code the error message beyond is shown  and import is stopped.

Code:
_install.packages("Thermimage")
library(Thermimage)
image <- paste0(system.file("..........thermo.jpg", package="Thermimage"))
cams<-flirsettings(".............thermo.jpg", "........./exiftool-12.03/", camvals="")
cams
img<-readflirJPG("............thermo.jpg", "........../exiftool-12.03/")

Error message in console:
> img<-readflirJPG("........../thermo.jpg", ".............../exiftool-12.03/")
Error in if (cams$Info$RawThermalImageType == "TIFF") { : 
  argument is of length zero

So far I havent been able to determine where the problem is situated, therefore I am looking forward for answers or suggestions.

Thanks a lot in advance.

**Comment by gtatters** [comment]
these errors are sometimes pathing errors (ie. exiftool is not properly installed).  I would first suggest you verify exiftool is installed first, and don't specify the location to see if it can pick it up in the normal location (C:/windows/System32).  I only included the customised path example to allow users to attempt to troubleshoot, but I advise you install exiftool in an appropriate folder in windows that is in the PATH environment (c:/windows).

Sometimes people suggest they are loading a flir jpg, but it is not a radiometric image, which might be the problem.  Have you tried the example in the flirsettings function to verify this?

## Example using the flirsettings function:

```
library(Thermimage)
## Sample flir jpg included with Thermimage package:

imagefile<-paste0(system.file("extdata/IR_2412.jpg", package="Thermimage"))

## Extract meta-tags from thermal image file ##
cams<-flirsettings(imagefile, exiftool="installed", camvals="")
```

  If you have spaces in file or folder names, it might be a problem. I would also suggest looking at other closed issues for help, as similar issues have come up.

The error message you are getting, assuming R can find the file and path, suggests that the jpg is not a radiometric jpg, but without a sample file I cannot be sure.

**Comment by lossberger** [comment]
Hi,

Thanks for the answer and the guidlines provided.

Indeed it was a combination of a pathing problem as well as a problem regarding the FLIR jpg.

Thanks a lot.
