### ISSUE TITLE
GPSLatitude and GPSLongitude not being read properly by flirsettings()

### ISSUE THREAD

**Issue by malonzo47** [gtatters/Thermimage#20]
Could be an issue on my end but not sure how...

For example:
cams$Info$GPSLatitude = 40959.29 in R

In the Composite:GPSLatitude tag (the only one I know how to view in exiftools cmd), it is:
40 deg 9' 59.28" N

So, it seems that the non-numeric DMS information is not being parsed correctly. 

Thanks!
Mike

**Comment by gtatters** [comment]
could you supply a sample file.  I don't provide much support for latitude/longitude extraction from flir files since they don't always follow a standard convention, and I mainly take what exiftool provides as a simple text.

**Comment by malonzo47** [comment]
Arghh... I dropped the ball on this, sorry. I'll give this another try in a
few months once I get my thermal camera back from the shop. Hopefully it
can just remain closed!

Mike

**Comment by gtatters** [comment]
Oh I can re-open it.  I just don't provide much help on GPS data in these files, since my experience has shown them to be highly variable and it's whatever Exiftool outputs that I'm trying to capture with these functions. But I can certainly investigate it with a sample file when you revisit.

**Comment by malonzo47** [comment]
No no, it's on me! I was just lamenting my own lack of follow up here. If I
were you, I'd just close it out for right now due to lack of "customer"
response. :-)

Mike
