### ISSUE TITLE
Package not extracting thermal image data

### ISSUE THREAD

**Issue by RussellGrayxd** [gtatters/Thermimage#21]
I have a dji mavic 2 enterprise advanced and collected a few thermal images I would like to analyze in R (see example attached). However, when I try to read in the data I get and error message (see code and error below):

##########################
##########################
setwd("D:/Detections")
list.files()
library(Thermimage)
library(fields)
f <- "D:/Detections/DJI_0067_T_S.JPG"
img <- readflirJPG(f, exiftoolpath="installed")

**Warning: [minor] Bad MakerNotes directory - D:/Detections/DJI_0067_T_S.JPG
Error in if (cams$Info$RawThermalImageType == "TIFF") { : 
  argument is of length zero
In addition: Warning message:
In readflirJPG(f, exiftoolpath = "installed") :
  Exiftool cannot extract raw thermal image data.
  Image does not contain FLIR radiometric data.
  Check with the user manual or manufacturer
  or ensure camera is set to save radiometric information.**

There is nothing wrong with the radiometric data, I have read this same image into the DJI thermal analysis tool without issue. 
I am running Windows 10. with R 4.0.3 and freshly installed Thermimage.

![DJI_0067_T_S](https://user-images.githubusercontent.com/30756433/166414495-bd703374-3b6c-4691-8b31-2d75bd98d36c.JPG)

**Comment by gtatters** [comment]
As the error code suggests, exiftool cannot convert this image type using the assumptions built into Thermimage package. The package was only built for FLIR research style cameras, not the drone cameras.
