### ISSUE TITLE
Getting random frame extraction times

### ISSUE THREAD

**Issue by nkhan076** [gtatters/Thermimage#3]
Hi, 
I am trying to get frame times following the code given as example. But I am getting random times for extracted frames. My file is pretty large i.e. 64MB.
How can I solve this?

Thanks.

**Comment by gtatters** [comment]
Is there any way you can attach a sample file provide the path to the file?  It is difficult to diagnose without more information.  

Operating system?  
Folder path (are their spaces in the name?)? 
Is it a SEQ file?  Some programs alter the SEQ files and might not be recognised. 
Have you tried using the command line "exiftool" first to see what it provides?

Files are influenced by the camera type and the software used to create them, so you may need to attach a link to a sample file you don't mind sharing.

**Comment by gtatters** [comment]
I'm looking into a fix, but need to completely re-write the function to be more flexible and search for frame time differently.  I would appreciate any test file you may have whether sent via a wetransfer.com or google drive share.  so far, I think I have a working version but I need to test it with different files from different cameras/computers.

**Comment by gtatters** [comment]
I have significantly changed and updated how frameLocates, getTimes, getFrames, and locate.fid work internally now.  I need to update the help files to explain changes, but in my tests on 5 different seq files collected from samples I have on file, the functions appear to be working now.  Please try v3.2.0 from github.
